### ISSUE TITLE
Swift 3, server side fork

### ISSUE THREAD

**Issue by iamjono** [thellimist/SwiftRandom#17]
Letting you know, I have created a server side, Swift 3 version of this excellent lib.
Forked to https://github.com/iamjono/SwiftRandom
I have also added a bunch of tests :)

Thanks!

**Comment by thellimist** [comment]
Happy to know the lib is useful 🙂. 

If you want you can make a PR to upgrade the lib to Swift3 since you already made the changes in your own repo 😉.

**Comment by iamjono** [comment]
Yep I will soon... 3 thinks complicate things a little - a) using with Swift Package Manager means it has to be on master, and it needs a very specific layout, and b) I transitioned to using AppKit instead of using UIKit, c) I dropped a couple of methods because they're iOS related (i.e. not server side).
So I might re-fork and do a franked-patch so you get the benefit of my changes, in the repo layout you have (incl the tests)

**Comment by thellimist** [comment]
I haven't had a chance to look at Swift 3 yet. (b) and (c) complicate things like you said. We'll support Swift 3 in the feature. Your fork is a bit different than how this lib should be after migrating to Swift 3.0.

Thanks anyway. Also nice job with the fork.
