### ISSUE TITLE
Add email generator

### ISSUE THREAD

**Issue by NosovPavel** [thellimist/SwiftRandom#24]
Sometimes I need to test api or just fill the screen with fake data, like users and in this case I need to show fake email address. Can you add it?

**Comment by thellimist** [comment]
I'm amazed how email was not added till now.

Under `Fake random data generators` you can create `public static func randomFakeEmail()` function. 

You can use `String.random(withCharactersInString: "abc", ofLength: 16)` where `abc` should be replaced with characters email addresses support. Then append well known emails `@gmail`, `@hotmail` etc. with closing tlds like `.com`, `.co.uk`. It's fairly simple. PR's are accepted :)

**Comment by NosovPavel** [comment]
Thanks, I hope it will be soon in the library.
PS: I used the same solution to solve my task now 👍
