### ISSUE TITLE
Build as a Framework

### ISSUE THREAD

**Issue by mokagio** [thellimist/SwiftRandom#3]
Neat 👍I think this projects has a lot of potential, but currently I wouldn't use it because it'd require me to either copy and paste or use a git submodule 😕.

If you'd build it as a framework, thus supporting [Carthage](https://github.com/Carthage/Carthage) and [CocoaPods](https://cocoapods.org/), it would be easier for developers to adopt SwiftRandom. :smile:

**Comment by thellimist** [comment]
https://github.com/thellimist/SwiftRandom/commit/0f6f4ca89a2c1958bcea1b87b4040365769f4720
